application: test-authentic
version: 1
runtime: python27
api_version: 1
threadsafe: true


builtins:
- django_wsgi: on
- remote_api: on

libraries:
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "2.6"

handlers:
- url: /static
  static_dir: static
- url: /static/admin
  static_dir: static/admin
  expiration: 0
- url: /.*
  script: main.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'auth_test.settings'