application: test-authentic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
- url: /static
  static_dir: static
- url: /static/admin
  static_dir: static/admin
  expiration: 0
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

builtins:
- django_wsgi: on

libraries:
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "latest"
- name: ssl
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'auth_test.settings'